# -*- coding: utf-8 -*-
"""PJBLDW(5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjjjGDomni4G_VLcLdpPnW-wCKRLr4T8

# Pre-processing Data Kapal Titanic Untuk Pembuatan Model Lebih Lanjut

### Data Collecting
"""

import pandas as pd

df_train = pd.read_csv('/train.csv')
df_train

"""### Data Understanding"""

df_train.describe()

"""### Data Cleaning"""

df_train.isnull().sum()

df_train.drop(['Cabin'], axis = 1, inplace = True)

df_train['Embarked'].value_counts()

df_train['Embarked'].fillna('S', inplace = True)

df_train = df_train.drop(['PassengerId', 'Name', 'Ticket'], axis=1)

sex = {"Sex": {"male":0, "female":1}}
df_train.replace(sex, inplace = True)

df_train.head(10)

pria = df_train['Age'].loc[df_train['Sex'] == 0].mean()
wanita = df_train['Age'].loc[df_train['Sex'] == 1].mean()
print("Pria = ", pria, "Wanita = ", wanita)

df_train['Age'].loc[ (df_train['Sex'] == 0) & (df_train['Age'].isnull() == True) ] = 31

df_train['Age'].loc[ (df_train['Sex'] == 1) & (df_train['Age'].isnull() == True) ] = 28

df_train['Fare'] = df_train['Fare'].astype(int)
df_train['Age'] = df_train['Age'].astype(int)

df_train['Age'].hist(bins=20)

df_train['Age'].loc[df_train['Survived'] == 1].hist(bins=40)

"""### Transformasi Data"""

umur = [0, 5, 15, 25, 30, 35, 45, 50, 100]
umur_label = ['0-5', '5-15', '15-25', '25-30', '30-35', '35-45', '45-50', '>50']
kelompok_umur = pd.cut(df_train['Age'], umur, labels=umur_label)
df_train['KelompokUmur'] = kelompok_umur
df_train['KelompokUmurKode'] = df_train['KelompokUmur'].cat.codes
df_train['KelompokUmur'].value_counts()

df_train['Fare'].hist(bins=20)

harga = [0, 10, 30, 35, 80, 500]
harga_label = ['0-10', '10-30', '30-35', '35-80', '>80']
kelompok_harga = pd.cut(df_train['Fare'], harga, labels=harga_label)
df_train['KelompokHarga'] = kelompok_harga
df_train['KelompokHargaKode'] = df_train['KelompokHarga'].cat.codes

JumlahOrang = df_train['SibSp'].astype(int) + df_train['Parch'].astype(int) + 1
df_train['JumlahOrang'] = JumlahOrang.astype(int)

df_train

df_train.loc[df_train['Survived'] == 1]

df_train['Pclass'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['Sex'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['Age'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['SibSp'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['Parch'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['Fare'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['Embarked'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['KelompokUmur'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['KelompokHarga'].loc[df_train['Survived'] == 1].hist(bins=40)

df_train['JumlahOrang'].loc[df_train['Survived'] == 1].hist(bins=40)

